#sudo docker run  -e app=web -p 5000:5000 -e PORT=5000 --name webapp -it  ahhatem/webapp
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api
spec:
    replicas: 1
    selector:
        matchLabels:
            component: api
    template:
        metadata:
            labels:
                component: api
        spec:
            containers:
                - name: api
                  image: ahhatem/webapp:$tag
                  ports:
                      - containerPort: 5000
                  env:
                      - name: app
                        value: api
                      - name: PORT
                        value: "5000"
                      - name: DB
                        value: postgres://testdbuser:testdbuserpassword@postgres-db-lb:5432/testdb
---
apiVersion: v1
kind: Service
metadata:
    name: api-lb
spec:
    selector:
        component: api
    type: LoadBalancer
    ports:
        - port: 5001
          targetPort: 5000
