apiVersion: apps/v1
kind: Deployment
metadata:
    name: web
spec:
    replicas: 1
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: web
                  image: ahhatem/webapp:$tag
                  ports:
                      - containerPort: 5000
                  env:
                      - name: app
                        value: web
                      - name: PORT
                        value: "5000"
                      - name: API_HOST
                        value: http://api-lb:5001
---
apiVersion: v1
kind: Service
metadata:
    name: web-lb
spec:
    selector:
        component: web
    type: LoadBalancer
    ports:
        - port: 5002
          targetPort: 5000
